apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jenkins
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLables: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
